ForeverGaming/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using ForeverGaming.Models;

namespace ForeverGaming.Controllers
{
    public class GameController : Controller
    {
        private GameUnitOfWork data { get; set; }
        public GameController(GameContext ctx) => data = new GameUnitOfWork(ctx);

        public RedirectToActionResult Index() => RedirectToAction("List");

        // dto has properties for the paging, sorting, and filtering route segments defined in the Startup.cs file
        public ViewResult List(GameGridDTO values)
        {
            // get grid builder, which loads route segment values and stores them in session
            var builder = new GameGridBuilder(HttpContext.Session, values,
                defaultSortField: nameof(Game.Name));

            // create a GameQueryOptions object to build a query expression for a page of data
            var options = new GameQueryOptions
            {
                Includes = "Genre, Type, Format, Rating, Publisher",
                OrderByDirection = builder.CurrentRoute.SortDirection,
                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize
            };

            // call the SortFilter() method of the GameQueryOptions object and pass it the builder
            // object. It uses the route information and the properties of the builder object to 
            // add sort and filter options to the query expression. 
            options.SortFilter(builder);

            // create view model and add page of game data, data for drop-downs, 
            // the current route, and the total number of pages. 
            var vm = new GameListViewModel
            {
                Games = data.Games.List(options),
                Genres = data.Genres.List(new QueryOptions<Genre>
                {
                    OrderBy = g => g.Name
                }),
                Types = data.Types.List(new QueryOptions<Type>
                {
                    OrderBy = t => t.Name
                }),
                Formats = data.Formats.List(new QueryOptions<Format>
                {
                    OrderBy = f => f.Name
                }),
                Ratings = data.Ratings.List(new QueryOptions<Rating>
                {
                    OrderBy = r => r.Name
                }),
                Publishers = data.Publishers.List(new QueryOptions<Publisher>
                {
                    OrderBy = p => p.Name
                }),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.Games.Count)
            };

            // pass view model to view
            return View(vm);
        }

        public ViewResult Details(int id)
        {
            var game = data.Games.Get(new QueryOptions<Game>
            {
                Includes = "Genre, Type, Format, Rating, Publisher",
                Where = b => b.GameId == id
            });

            return View(game);
        }

        [HttpPost]
        public RedirectToActionResult Filter(string[] filter, bool clear = false)
        {
            // get current route segments from session
            var builder = new GameGridBuilder(HttpContext.Session);

            // clear or update filter route segment values. 
            if (clear)
            {
                builder.ClearFilterSegments();
            }
            else
            {
                builder.LoadFilterSegments(filter);
            }


            // save route data back to session and redirect to Game/List action method,
            // passing dictionary of route segment values to build URL
            builder.SaveRouteSegments();

            return RedirectToAction("List", builder.CurrentRoute);
        }

        [HttpPost]
        public RedirectToActionResult PageSize(int pagesize)
        {
            var builder = new GameGridBuilder(HttpContext.Session);

            builder.CurrentRoute.PageSize = pagesize;
            builder.SaveRouteSegments();

            return RedirectToAction("List", builder.CurrentRoute);
        }
    }
}

ForeverGaming/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    // nested layout view
    Layout = "_Layout";

    // use current controller determine if tab is active
    var current = ViewContext.RouteData.Values["controller"]?.ToString();
}

@* since many admin views deal with user entry and data validation,
    jQuery validation libraries are included here rather than in individual views. *@
@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<ul class="nav nav-tabs mt-2 bg-dark">
    <li class="nav-item bg-dark border-dark">
        <a asp-action="Index" asp-controller="Game"
           class="nav-link @Nav.Active("Game", current)" style="color: aqua; font-weight: bold">
            Manage Games
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="Type"
           class="nav-link @Nav.Active("Type", current)" style="color: aqua; font-weight: bold">
            Manage Types
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="Genre"
           class="nav-link @Nav.Active("Genre", current)" style="color: aqua; font-weight: bold">
            Manage Genres
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="Format"
           class="nav-link @Nav.Active("Format", current)" style="color: aqua; font-weight: bold">
            Manage Formats
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="Rating"
           class="nav-link @Nav.Active("Rating", current)" style="color: aqua; font-weight: bold">
            Manage Ratings
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="Publisher"
           class="nav-link @Nav.Active("Publisher", current)" style="color: aqua; font-weight: bold">
            Manage Publishers
        </a>
    </li>
    <li class="nav-item bg-dark">
        <a asp-action="Index" asp-controller="User"
           class="nav-link @Nav.Active("User", current)" style="color: aqua; font-weight: bold">
            Manage Users
        </a>
    </li>
</ul>

@RenderBody()